### ISSUE TITLE
Multiple definition errors for Barkeep functions when included in multiple .cpp files

### ISSUE THREAD

**Issue by aghaeifar** [oir/barkeep#93]
Hi,

Thanks for the amazing progress bar library!

I’m using Barkeep in a C++ project with multiple source files. I include barkeep.h in multiple .cpp files, as each file uses its own progress bar. However, I get the following compilation error:

for example:
```shell
CMakeFiles/SpinWalk.dir/src/sim/monte_carlo.cu.o: in function `barkeep::as_duration(std::variant<std::chrono::duration<double, std::ratio<1l, 1l> >, double>)':
tmpxft_0009d674_00000000-6_monte_carlo.compute_89.cudafe1.cpp:(.text+0x399): multiple definition of `barkeep::as_duration(std::variant<std::chrono::duration<double, std::ratio<1l, 1l> >, double>)'; CMakeFiles/SpinWalk.dir/src/phantom/phantom_sphere.cpp.o:phantom_sphere.cpp:(.text+0xb): first defined here
``` 
If I include Barkeep in only one .cpp file, the issue does not occur.
There are multiple errors like this for other Barkeep functions as well.
There’s no recursive inclusion of headers.

I suggest mark the functions as `inline`.

**Comment by oir** [comment]
Oops! This sounds like a bug. Hoping to take a closer look tomorrow, thanks for reporting!

**Comment by oir** [comment]
@aghaeifar, I was able to reproduce this, and confirm that #94 fixes it on my end. Can you give that a try?

**Comment by aghaeifar** [comment]
Thanks for the bug fix.
The #94 resolved the issue in my side too.
